config/routes.rb
TodolistApp::Application.routes.draw do
  resources :todolists
  root 'todolists#index'

  

end

app/models/todolist.rb
class Todolist < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  before_action :set_todolist, only: [:show, :edit, :update, :destroy]

  # GET /todolists
  # GET /todolists.json
  def index
    @todolists = Todolist.all
  end

  # GET /todolists/1
  # GET /todolists/1.json
  def show
  end

  # GET /todolists/new
  def new
    @todolist = Todolist.new
  end

  # GET /todolists/1/edit
  def edit
  end

  # POST /todolists
  # POST /todolists.json
  def create
    @todolist = Todolist.new(todolist_params)

    respond_to do |format|
      if @todolist.save
        format.html { redirect_to @todolist, notice: 'Todolist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @todolist }
      else
        format.html { render action: 'new' }
        format.json { render json: @todolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todolists/1
  # PATCH/PUT /todolists/1.json
  def update
    respond_to do |format|
      if @todolist.update(todolist_params)
        format.html { redirect_to @todolist, notice: 'Todolist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @todolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todolists/1
  # DELETE /todolists/1.json
  def destroy
    @todolist.destroy
    respond_to do |format|
      format.html { redirect_to todolists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todolist
      @todolist = Todolist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todolist_params
      params.require(:todolist).permit(:name, :read, :effort, :assigned_to, :created_at, :due_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodolistApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todolists/_form.html.erb
<%= form_for(@todolist) do |f| %>
  <% if @todolist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todolist.errors.count, "error") %> prohibited this todolist from being saved:</h2>

      <ul>
      <% @todolist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :read %><br>
    <%= f.check_box :read %>
  </div>
  <div class="field">
    <%= f.label :effort %><br>
    <%= f.text_field :effort %>
  </div>
  <div class="field">
    <%= f.label :assigned_to %><br>
    <%= f.text_field :assigned_to %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.datetime_select :due_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todolists/edit.html.erb
<h1>Editing todolist</h1>

<%= render 'form' %>

<%= link_to 'Show', @todolist %> |
<%= link_to 'Back', todolists_path %>

app/views/todolists/index.html.erb
<h1>Todo lists</h1>

<table>
  <thead>
    <tr>
      <th>Task Name</th>
      <th>Read</th>
      <th>Effort</th>
      <th>Assigned to</th>
      <th>Created at</th>
      <th>Due date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @todolists.each do |todolist| %>
      <tr>
        <td><%= todolist.name %></td>
        <td><%= todolist.read %></td>
        <td><%= todolist.effort %></td>
        <td><%= todolist.assigned_to %></td>
        <td><%= todolist.created_at %></td>
        <td><%= todolist.due_date %></td>
        <td><%= link_to 'Show', todolist %></td>
        <td><%= link_to 'Edit', edit_todolist_path(todolist) %></td>
        <td><%= link_to 'Destroy', todolist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todolist', new_todolist_path %>

app/views/todolists/new.html.erb
<h1>Ricky's todo list</h1>

<%= render 'form' %>

<%= link_to 'Back', todolists_path %>

app/views/todolists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @todolist.name %>
</p>

<p>
  <strong>Read:</strong>
  <%= @todolist.read %>
</p>

<p>
  <strong>Effort:</strong>
  <%= @todolist.effort %>
</p>

<p>
  <strong>Assigned to:</strong>
  <%= @todolist.assigned_to %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @todolist.created_at %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @todolist.due_date %>
</p>

<%= link_to 'Edit', edit_todolist_path(@todolist) %> |
<%= link_to 'Back', todolists_path %>